version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    depends_on:
      - browser

  browser:
    image: mcr.microsoft.com/playwright:v1.50.1-jammy
    ports:
      - "3001:3001"
    # Keep container running
    command: tail -f /dev/null
